#!/usr/bin/env bash
#
# Set netwatch up on a Raspberry Pi (or any Debian-based system).
#
# netwatch runs straight from this git clone -- it is pure Python, so `git pull`
# is the entire update process. This script checks dependencies and puts a
# `netwatch` command on your PATH.
#
#   git clone https://github.com/t0mbo192/netwatch.git
#   cd netwatch && ./install-pi.sh
#
# It never runs sudo itself: anything missing is reported with the exact command
# for you to run.

set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BIN_DIR="$HOME/.local/bin"

say()  { printf '  %s\n' "$1"; }
fail() { printf '\n[!] %s\n' "$1" >&2; exit 1; }

printf '\nnetwatch setup\n==============\n\n'

# --- required ----------------------------------------------------------------
command -v python3 >/dev/null 2>&1 || fail "python3 is not installed."
if ! command -v tshark >/dev/null 2>&1; then
    printf 'tshark is required to read packets.\n\n'
    printf 'Install it with:\n\n    sudo apt install tshark\n\n'
    fail "Re-run this script once it is installed."
fi
say "tshark             : $(command -v tshark)"
say "python3            : $(python3 --version 2>&1)"

# Capturing live traffic as a normal user needs the wireshark group. Reading
# saved captures works either way.
if getent group wireshark >/dev/null 2>&1; then
    if id -nG "$USER" | tr ' ' '\n' | grep -qx wireshark; then
        say "capture permission : ok (in wireshark group)"
    else
        say "capture permission : live capture needs the wireshark group"
        say "        sudo usermod -aG wireshark $USER   (then log out and back in)"
    fi
fi

# --- optional: organisation names for bare addresses -------------------------
if python3 -c "import maxminddb" >/dev/null 2>&1; then
    if python3 -c "
import sys; sys.path.insert(0, '$REPO_DIR')
import asn_lookup; sys.exit(0 if asn_lookup.available() else 1)" >/dev/null 2>&1; then
        say "ASN database       : ok"
    else
        say "ASN database       : missing - bare addresses will stay unnamed"
        say "        python3 $REPO_DIR/netwatch.py asn --fetch"
    fi
else
    say "maxminddb          : not installed (optional)"
    say "        sudo apt install python3-maxminddb"
    say "        python3 $REPO_DIR/netwatch.py asn --fetch"
fi

# --- command on PATH ---------------------------------------------------------
mkdir -p "$BIN_DIR"
cat > "$BIN_DIR/netwatch" <<EOF
#!/usr/bin/env bash
# Generated by install-pi.sh -- runs netwatch from its git clone.
exec python3 "$REPO_DIR/netwatch.py" "\$@"
EOF
chmod +x "$BIN_DIR/netwatch"
say "command            : $BIN_DIR/netwatch"

case ":$PATH:" in
    *":$BIN_DIR:"*) ;;
    *) say "note: $BIN_DIR is not on your PATH -- add it to ~/.profile" ;;
esac

version=$(python3 -c "import sys; sys.path.insert(0, '$REPO_DIR'); from netwatch_version import __version__; print(__version__)")

cat <<EOF

Done -- netwatch $version is installed.

  See interfaces      netwatch interfaces
  Watch live          sudo netwatch live -i eth0
  Read a capture      netwatch read capture.pcapng
  Update              cd $REPO_DIR && git pull

EOF
