#!/usr/bin/env bash
#
# Set netwatch up on a Raspberry Pi (or any Debian-based desktop).
#
# The Pi runs netwatch from this git clone rather than from a build: the app is
# pure Python, so `git pull` is the entire update process. This script only
# checks the dependencies and adds a menu entry plus a `netwatch` command.
#
#   git clone https://github.com/t0mbo192/netwatch.git
#   cd netwatch && ./install-pi.sh
#
# It never runs sudo itself -- if something is missing it prints the exact
# command for you to run.

set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
APP="$REPO_DIR/connection_viewer.py"
BIN_DIR="$HOME/.local/bin"
DESKTOP_DIR="$HOME/.local/share/applications"
DROP_DIR="$HOME/Documents/Captures"

say()  { printf '  %s\n' "$1"; }
fail() { printf '\n[!] %s\n' "$1" >&2; exit 1; }

printf '\nnetwatch setup\n==============\n\n'

# --- dependencies ------------------------------------------------------------
missing=()
command -v tshark >/dev/null 2>&1 || missing+=("tshark")
python3 -c "import tkinter" >/dev/null 2>&1 || missing+=("python3-tk")

if [ ${#missing[@]} -gt 0 ]; then
    printf 'Missing dependencies: %s\n\n' "${missing[*]}"
    printf 'Install them with:\n\n    sudo apt install %s\n\n' "${missing[*]}"
    fail "Re-run this script once they are installed."
fi
say "tshark found       : $(command -v tshark)"
say "python3 + tkinter  : ok"

# Reading captures as a non-root user needs membership of the wireshark group.
# Only relevant for live capture; opening saved files works either way.
if getent group wireshark >/dev/null 2>&1; then
    if ! id -nG "$USER" | tr ' ' '\n' | grep -qx wireshark; then
        say "note: add yourself to the 'wireshark' group to capture live traffic:"
        say "        sudo usermod -aG wireshark $USER   (then log out and back in)"
    fi
fi

# --- launcher command --------------------------------------------------------
mkdir -p "$BIN_DIR"
cat > "$BIN_DIR/netwatch" <<EOF
#!/usr/bin/env bash
# Generated by install-pi.sh -- runs netwatch from its git clone.
exec python3 "$APP" "\$@"
EOF
chmod +x "$BIN_DIR/netwatch"
say "command installed  : $BIN_DIR/netwatch"

case ":$PATH:" in
    *":$BIN_DIR:"*) ;;
    *) say "note: $BIN_DIR is not on your PATH; add it to ~/.profile" ;;
esac

# --- desktop entry -----------------------------------------------------------
mkdir -p "$DESKTOP_DIR"
cat > "$DESKTOP_DIR/netwatch.desktop" <<EOF
[Desktop Entry]
Type=Application
Name=netwatch
Comment=See which sites this machine connected to, and what connected to it
Exec=python3 $APP
Path=$REPO_DIR
Terminal=false
Categories=Network;Monitor;
EOF
say "menu entry         : $DESKTOP_DIR/netwatch.desktop"

mkdir -p "$DROP_DIR"
say "capture drop folder: $DROP_DIR"

version=$(python3 -c "import sys; sys.path.insert(0, '$REPO_DIR'); from netwatch_version import __version__; print(__version__)")

cat <<EOF

Done -- netwatch $version is installed.

  Run it          netwatch          (or find it in the applications menu)
  Open a capture  drop a .pcapng into $DROP_DIR and launch netwatch;
                  it opens the newest one automatically
  Update          cd $REPO_DIR && git pull
                  netwatch notices new commits on startup and tells you

EOF
